$(function () {
  // ici mon script
  // EXERCICE 1 - LORSQUE JE CLIQUE SUR LA ZONE1, LE TITRE H1 DOIT SE METTRE EN VERT, AU CENTRE, ET AVOIR UNE TAILLE DE 80PX
  // EXERCICE 2 - LORSQUE JE CLIQUE SUR LA ZONE2 LE BACKGROUND DE LA PAGE DOIT CHANGER DE COULEUR
  // EXERCICE 3 - JE CREE UN BOUTON (SUBMIT et NON BUTTON) DE FORMULAIRE ET LORSQUE JE CLIQUE DESSUS LE BACKGRUIOND DE LA PAGE CHANGE DE COULEUR
  // EXERCICE 4 - JE CREE UN CHAMP DE FORMULAIRE AINSI QU'UN BOUTON (SUBMIT et NON BUTTON) DE FORMULAIRE ET LORSQUE JE CLIC DESSUS LE BACKGROUND DE LA PAGE CHANGE DE COULEUR AVEC LA COULEUR SAISIE DANS LE CHAMP
});

// Exercice 1
$(".zone1").on("click", function () {
  $("h1").css("color", "green");
  $("h1").text("font-size", "80");
});

// Exercice 2
$(".zone2").on("click", function () {
  $("h1").css("background", "green");
  $("h1").text("");
});
